# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: rollindscopeschool
# "service" is the name of this project. This will also be added to your AWS resource names.
service: product-service
frameworkVersion: "4"

provider:
    name: aws
    runtime: nodejs20.x

    stage: dev
    region: eu-central-1

functions:
    getProductsList:
        handler: getProductsListHandler.getProductsList
        events:
            - httpApi:
                  path: /products
                  method: get
    getProductsById:
        handler: getProductsByIdHandler.getProductsById
        events:
            - httpApi:
                  path: /products/{id}
                  method: get
